# Generated by Django 4.0.6 on 2023-12-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydevops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=255),
        ),
    ]
